# NumPy refresher

Source: http://www.deeplearning.net/software/theano/tutorial/numpy.html

Here are some quick guides to NumPy:
  * [Numpy quick guide for Matlab users](http://www.scipy.org/NumPy_for_Matlab_Users>)
  * [Numpy User Guide](http://docs.scipy.org/doc/numpy/user/index.html>)
  * [More detailed Numpy tutorial](http://www.scipy.org/Tentative_NumPy_Tutorial>)
  * [100 NumPy exercises](https://github.com/rougier/numpy-100>)
  * [Numpy tutorial](http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html>)

## Matrix conventions for machine learning

Rows are horizontal and columns are vertical. Every row is an example. Therefore, ``inputs[10,5]`` is a matrix of 10 examples where each example has dimension 5. If this would be the input of a neural network then the weights from the input to the first hidden layer would represent a matrix of size ``(5, n_hidden_nodes)``.

Consider this array:

In [7]:
import numpy as np

arr = np.asarray([[1., 2], [3, 4], [5, 6]])
print(arr)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [8]:
print(arr.shape)

(3, 2)


This is a 3x2 matrix, i.e. there are 3 rows and 2 columns.

To access the entry in the 3rd row (row #2) and the 1st column (column #0):

In [9]:
arr[2, 0]

5.0

To remember this, keep in mind that we read left-to-right, top-to-bottom, so each thing that is contiguous is a row. That is, there are 3 rows and 2 columns.

## Broadcasting

Numpy does *broadcasting* of arrays of different shapes during arithmetic operations. What this means in general is that the smaller array (or scalar) is broadcasted across the larger array so that they have compatible shapes. The example below shows an instance of *broadcasting*:

In [11]:
b = 2.0
arr * b

array([[  2.,   4.],
       [  6.,   8.],
       [ 10.,  12.]])

The smaller array ``b`` (actually a scalar here, which works like a 0-d array) in this case is broadcasted to the same size as a during the multiplication. This trick is often useful in simplifying how expression are written. More detail about broadcasting can be found in the [numpy user guide](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

## Matrix operations

Transpose of a matrix:

In [12]:
arr.T

array([[ 1.,  3.,  5.],
       [ 2.,  4.,  6.]])

In [13]:
arr.transpose()

array([[ 1.,  3.,  5.],
       [ 2.,  4.,  6.]])

Matrix multiply:

In [15]:
np.dot(arr, np.array([0.5, 1]))

array([ 2.5,  5.5,  8.5])

Inverse of a square matrix:

In [19]:
sqr_matrix = np.array([[1, 4, 0], [9, 7, -1], [3, 6, -8]])
np.linalg.inv(sqr_matrix)

array([[-0.22123894,  0.14159292, -0.01769912],
       [ 0.30530973, -0.03539823,  0.00442478],
       [ 0.1460177 ,  0.02654867, -0.12831858]])